### ISSUE TITLE
"Create a new Instrument on each take"

### ISSUE THREAD

**Issue by AndyJBuchanan** [verdog/renoise-hardware-sampler#1]
Hello! Awesome tool!

Being very new to Renoise (like 3 days), it did take me a while to figure out I needed to make sure "Create a new Instrument on each take" option in Recording Options needed to be unchecked. 

If I left it checked, the Lua exploded as obviously the newly instrument had no sample slots.

**Comment by verdog** [comment]
Oh, right... completely forgot that setting was a thing, I turned it off ages ago and never looked back! 

As far as I know, there is no way to control those settings with the Renoise API, or even check what they are. I will double check that though. If not, I can at least add something to the README and make the tool fail more gracefully. 

Thanks for reporting this!

**Comment by AndyJBuchanan** [comment]
No problem! 

My Lua is a bit rusty, and I haven't investigated the API yet myself but if the option is inaccessible, perhaps before each sample recording you could check whether the index exists and pop up a warning for the user to check the option, or maybe even make a note of the selected Instrument at the start of the capture session and switch back to it if the selection changes?

**Comment by chris-roerig** [comment]
I made note to this in the README on this commit https://github.com/verdog/renoise-hardware-sampler/pull/3/commits/609e792346ee23c8f9df36f7007298a0c99a467c

Still worth improving the error handling and is something I can add to a roadmap if we want to get one started

**Comment by verdog** [comment]
1.5 will now try to detect an instrument switch and warn you about it, with instructions on how to fix it.
