### ISSUE TITLE
Recordings not being persisted. Timing issue.

### ISSUE THREAD

**Issue by AndyJBuchanan** [verdog/renoise-hardware-sampler#2]
I have found that not every recording is stored to its sample slot successfully.

This appears to be a timing issue, in stop_note() if I increase the delay parameter to the call_in() to prep the next note the problem goes away and all the recordings are stored correctly.

Increasing from 50 to 150 seems to be enough for my system.

**Comment by verdog** [comment]
I will add a setting to the GUI to allow users to tweak that! Thanks for the catch.

**Comment by chris-roerig** [comment]
Check https://github.com/verdog/renoise-hardware-sampler/pull/3/commits/2d05f61b838504c495b8b35a0475cf0da2074193

**Comment by verdog** [comment]
Added the option in 1.5! :)
